### ISSUE TITLE
Add FEC file or db with 2014?

### ISSUE THREAD

**Issue by bruceskarin** [Solomon/opensecrets_to_postgres#1]
@Solomon First off, thank you for doing this. It has saved me a ton of time. I'm a user that prefers the easy option (downloading the dump), but I'd really like to update my analysis to include the 2014 data that Open Secrets has posted now.

I'm not sure about building the whole db from scratch, so would you be willing to either update your database and post it or add a more simple script for adding just a single new cycle to an existing database?

Thanks again,
-Bruce

**Comment by Solomon** [comment]
Hey Bruce,

The db is currently updated with 2014 data, so if you download a new dump, you should be all set.

**Comment by bruceskarin** [comment]
Got it, perfect, thank you once again.
